### ISSUE TITLE
Clean Spring exit

### ISSUE THREAD

**Issue by afaulconbridge** [enasequence/spring-boot-cookbook#1]
If you want to use [ExitCodeGenerator ](http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/ExitCodeGenerator.html) or lifecycle annotations such as `@PreDestroy` to cleanup resources (e.g. thread pools), then Spring-boot needs to manage the application exit process e.g. :

    public static void main(String[] args) throws Exception {
        SpringApplication springApplication = new SpringApplication(Application.class);
        springApplication.addListeners(new ApplicationPidFileWriter(PID_FILE));
        SpringApplication.exit(springApplication.run(args));
    }

This is particularly important for LSF processes, cron jobs, or command-line based applications.

**Comment by danielvaughan** [comment]
Thanks, I have added that in
